/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ANURUDDHA
 */
public class AddMarketReturn extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddBack
     */
    public AddMarketReturn() {
        initComponents();
    }

    void combo() {
        try {
            ResultSet rs = JDBC.getdata("SELECT * FROM items WHERE name LIKE '" + jTitem.getText() + "%' AND status='Active'");
            Vector v = new Vector();
            while (rs.next()) {
                v.add(rs.getString("name"));
            }
            jCGRN_item.setModel(new DefaultComboBoxModel(v));
            jCGRN_item.showPopup();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTitem = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jTqty = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jCGRN_item = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jButton22 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Add Market Return");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTitem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTitem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTitemKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTitemKeyReleased(evt);
            }
        });

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel71.setText("Qty");

        jTqty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTqty.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel69.setText("Item");

        jCGRN_item.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCGRN_item.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCGRN_itemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel69, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTqty, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTitem)
                    .addComponent(jCGRN_item, 0, 315, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(jTitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jCGRN_item, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel71))
                .addContainerGap())
        );

        jButton22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton22.setText("Save");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton22)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        try {
            if (jTitem.getText().isEmpty() || jTqty.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Some fields are empty", "Input error", JOptionPane.ERROR_MESSAGE);
            } else {
                String iid = "";
                double up = 0.0;
                ResultSet rs_check_one = JDBC.getdata("SELECT * FROM stock WHERE name='" + jTitem.getText().toString().trim() + "'");
                if (rs_check_one.next()) {
                    ResultSet rs_stock = JDBC.getdata("SELECT * FROM stock WHERE name='" + jTitem.getText().toString().trim() + "'");
                    while (rs_stock.next()) {
                        iid = rs_stock.getString("iid");
                        up = rs_stock.getDouble("unit_price");
                    }
                    JDBC.putdata("UPDATE stock SET qty=qty-'" + jTqty.getText().trim() + "' WHERE name='" + jTitem.getText().toString().trim() + "'");
                    ResultSet rs_check_two = JDBC.getdata("SELECT * FROM market_return WHERE iid='" + iid + "'");
                    if (rs_check_two.next()) {
                        JDBC.putdata("UPDATE market_return SET qty=qty+'" + jTqty.getText().trim() + "' WHERE iid='" + iid + "'");
                    } else {
                        JDBC.putdata("INSERT INTO market_return VALUES(0,"
                                + "'" + iid + "',"
                                + "'" + jTitem.getText().trim() + "',"
                                + "'" + up + "',"
                                + "'" + jTqty.getText().trim() + "',"
                                + "'Visible')");
                    }
                    jTqty.setText("");
                    jTitem.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "No such item found in stock", "Input error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jTitemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTitemKeyPressed
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jCGRN_item.grabFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTitem.setText(jCGRN_item.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jTitemKeyPressed

    private void jTitemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTitemKeyReleased
        combo();
    }//GEN-LAST:event_jTitemKeyReleased

    private void jCGRN_itemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCGRN_itemKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTitem.setText(jCGRN_item.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jCGRN_itemKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton22;
    private javax.swing.JComboBox jCGRN_item;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTitem;
    private javax.swing.JTextField jTqty;
    // End of variables declaration//GEN-END:variables
}
